#!/bin/bash

set -o pipefail

# Revert the AWS environment variables to the original values when this plugin
# ran before the command.

if [[ -n $RESTORE_ROLE_PLUGIN_OG_AWS_ACCESS_KEY_ID ]]; then
  export AWS_ACCESS_KEY_ID="${RESTORE_ROLE_PLUGIN_AWS_ACCESS_KEY_ID}"
  unset RESTORE_ROLE_PLUGIN_OG_AWS_ACCESS_KEY_ID
  echo "Restored original AWS_ACCESS_KEY_ID"
else
  unset AWS_ACCESS_KEY_ID
  echo "Unset AWS_ACCESS_KEY_ID to match original"
fi
if [[ -n $RESTORE_ROLE_PLUGIN_OG_AWS_SECRET_ACCESS_KEY ]]; then
  export AWS_SECRET_ACCESS_KEY="${RESTORE_ROLE_PLUGIN_OG_AWS_SECRET_ACCESS_KEY}"
  unset RESTORE_ROLE_PLUGIN_OG_AWS_SECRET_ACCESS_KEY
  echo "Restored original AWS_SECRET_ACCESS_KEY"
else
  unset AWS_SECRET_ACCESS_KEY
  echo "Unset AWS_SECRET_ACCESS_KEY to match original"
fi
if [[ -n $RESTORE_ROLE_PLUGIN_OG_AWS_SESSION_TOKEN ]]; then
  export AWS_SESSION_TOKEN="${RESTORE_ROLE_PLUGIN_OG_AWS_SESSION_TOKEN}"
  unset RESTORE_ROLE_PLUGIN_OG_AWS_SESSION_TOKEN
  echo "Restored original AWS_SESSION_TOKEN"
else
  unset AWS_SESSION_TOKEN
  echo "Unset AWS_SESSION_TOKEN to match original"
fi
if [[ -n $RESTORE_ROLE_PLUGIN_OG_AWS_REGION ]]; then
  export AWS_REGION="${RESTORE_ROLE_PLUGIN_OG_AWS_REGION}"
  unset RESTORE_ROLE_PLUGIN_OG_AWS_REGION
  echo "Restored original AWS_REGION"
else
  unset AWS_REGION
  echo "Unset AWS_REGION to match original"
fi
if [[ -n $RESTORE_ROLE_PLUGIN_OG_AWS_DEFAULT_REGION ]]; then
  export AWS_DEFAULT_REGION="${RESTORE_ROLE_PLUGIN_OG_AWS_DEFAULT_REGION}"
  unset RESTORE_ROLE_PLUGIN_OG_AWS_DEFAULT_REGION
  echo "Restored original AWS_DEFAULT_REGION"
else
  unset AWS_DEFAULT_REGION
  echo "Unset AWS_DEFAULT_REGION to match original"
fi
