#!/bin/bash

set -o pipefail

echo "~~~ Unsetting AWS role environment variabless ~~~"
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_REGION
unset AWS_DEFAULT_REGION
